version: '3.8'

services:
  nextjs-app:
    image: nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    command: npm run build

volumes:
  app_node_modules: {}
