export const fakedata = {
  _id: '0858010005580',
  _keywords: [
    '32',
    'and',
    'bar',
    'chocolate',
    'chocolonely',
    'cocoa',
    'fair',
    'fairtrade',
    'international',
    'it',
    'milk',
    'product',
    'snack',
    'sweet',
    'tony',
    'trade'
  ],
  added_countries_tags: [],
  additives_n: 1,
  additives_original_tags: ['en:e322i'],
  additives_tags: ['en:e322', 'en:e322i'],
  allergens: 'en:milk,en:soybeans',
  allergens_from_ingredients: 'en:soybeans, en:milk, soy lecithin',
  allergens_from_user: '(en) en:milk,en:soybeans',
  allergens_hierarchy: ['en:milk', 'en:soybeans'],
  allergens_lc: 'en',
  allergens_tags: ['en:milk', 'en:soybeans'],
  amino_acids_tags: [],
  brands: "Tony's Chocolonely",
  brands_tags: ['tony-s-chocolonely'],
  categories: 'Snacks,Sweet snacks,Cocoa and its products,Chocolates,Milk chocolates',
  categories_hierarchy: [
    'en:snacks',
    'en:sweet-snacks',
    'en:cocoa-and-its-products',
    'en:chocolates',
    'en:milk-chocolates'
  ],
  categories_lc: 'en',
  categories_old: 'Snacks, Sweet snacks, Cocoa and its products, Chocolates, Milk chocolates',
  categories_properties: {
    'agribalyse_proxy_food_code:en': '31004'
  },
  categories_properties_tags: [
    'all-products',
    'categories-known',
    'agribalyse-food-code-unknown',
    'agribalyse-proxy-food-code-31004',
    'agribalyse-proxy-food-code-known',
    'ciqual-food-code-unknown',
    'agribalyse-known',
    'agribalyse-31004'
  ],
  categories_tags: ['en:snacks', 'en:sweet-snacks', 'en:cocoa-and-its-products', 'en:chocolates', 'en:milk-chocolates'],
  checkers_tags: [],
  cities_tags: [],
  code: '0858010005580',
  codes_tags: [
    'code-13',
    '0858010005xxx',
    '085801000xxxx',
    '08580100xxxxx',
    '0858010xxxxxx',
    '085801xxxxxxx',
    '08580xxxxxxxx',
    '0858xxxxxxxxx',
    '085xxxxxxxxxx',
    '08xxxxxxxxxxx',
    '0xxxxxxxxxxxx'
  ],
  compared_to_category: 'en:milk-chocolates',
  complete: 0,
  completeness: 0.6875,
  correctors_tags: ['openfoodfacts-contributors', 'ponkcelot', 'lcmortensen'],
  countries: 'United States,New Zealand',
  countries_hierarchy: ['en:new-zealand', 'en:united-states'],
  countries_lc: 'en',
  countries_tags: ['en:new-zealand', 'en:united-states'],
  created_t: 1602101639,
  creator: 'kiliweb',
  data_quality_bugs_tags: [],
  data_quality_errors_tags: [],
  data_quality_info_tags: [
    'en:no-packaging-data',
    'en:environmental-score-extended-data-not-computed',
    'en:food-groups-1-known',
    'en:food-groups-2-known',
    'en:food-groups-3-unknown'
  ],
  data_quality_tags: [
    'en:no-packaging-data',
    'en:environmental-score-extended-data-not-computed',
    'en:food-groups-1-known',
    'en:food-groups-2-known',
    'en:food-groups-3-unknown',
    'en:ingredients-percent-analysis-not-ok',
    'en:environmental-score-origins-of-ingredients-origins-are-100-percent-unknown',
    'en:environmental-score-packaging-packaging-data-missing'
  ],
  data_quality_warnings_tags: [
    'en:ingredients-percent-analysis-not-ok',
    'en:environmental-score-origins-of-ingredients-origins-are-100-percent-unknown',
    'en:environmental-score-packaging-packaging-data-missing'
  ],
  data_sources: 'App - yuka, Apps, App - Open Food Facts',
  data_sources_tags: ['app-yuka', 'apps', 'app-open-food-facts'],
  debug_param_sorted_langs: ['en'],
  ecoscore_data: {
    adjustments: {
      origins_of_ingredients: {
        aggregated_origins: [
          {
            epi_score: '0',
            origin: 'en:unknown',
            percent: 100,
            transportation_score: 0
          }
        ],
        epi_score: 0,
        epi_value: 0,
        origins_from_categories: ['en:unknown'],
        origins_from_origins_field: ['en:unknown'],
        transportation_score: 0,
        transportation_scores: {
          ad: 0,
          al: 0,
          at: 0,
          ax: 0,
          ba: 0,
          be: 0,
          bg: 0,
          ch: 0,
          cy: 0,
          cz: 0,
          de: 0,
          dk: 0,
          dz: 0,
          ee: 0,
          eg: 0,
          es: 0,
          fi: 0,
          fo: 0,
          fr: 0,
          gg: 0,
          gi: 0,
          gr: 0,
          hr: 0,
          hu: 0,
          ie: 0,
          il: 0,
          im: 0,
          is: 0,
          it: 0,
          je: 0,
          lb: 0,
          li: 0,
          lt: 0,
          lu: 0,
          lv: 0,
          ly: 0,
          ma: 0,
          mc: 0,
          md: 0,
          me: 0,
          mk: 0,
          mt: 0,
          nl: 0,
          no: 0,
          pl: 0,
          ps: 0,
          pt: 0,
          ro: 0,
          rs: 0,
          se: 0,
          si: 0,
          sj: 0,
          sk: 0,
          sm: 0,
          sy: 0,
          tn: 0,
          tr: 0,
          ua: 0,
          uk: 0,
          us: 0,
          va: 0,
          world: 0,
          xk: 0
        },
        transportation_value: 0,
        transportation_values: {
          ad: 0,
          al: 0,
          at: 0,
          ax: 0,
          ba: 0,
          be: 0,
          bg: 0,
          ch: 0,
          cy: 0,
          cz: 0,
          de: 0,
          dk: 0,
          dz: 0,
          ee: 0,
          eg: 0,
          es: 0,
          fi: 0,
          fo: 0,
          fr: 0,
          gg: 0,
          gi: 0,
          gr: 0,
          hr: 0,
          hu: 0,
          ie: 0,
          il: 0,
          im: 0,
          is: 0,
          it: 0,
          je: 0,
          lb: 0,
          li: 0,
          lt: 0,
          lu: 0,
          lv: 0,
          ly: 0,
          ma: 0,
          mc: 0,
          md: 0,
          me: 0,
          mk: 0,
          mt: 0,
          nl: 0,
          no: 0,
          pl: 0,
          ps: 0,
          pt: 0,
          ro: 0,
          rs: 0,
          se: 0,
          si: 0,
          sj: 0,
          sk: 0,
          sm: 0,
          sy: 0,
          tn: 0,
          tr: 0,
          ua: 0,
          uk: 0,
          us: 0,
          va: 0,
          world: 0,
          xk: 0
        },
        value: 0,
        values: {
          ad: 0,
          al: 0,
          at: 0,
          ax: 0,
          ba: 0,
          be: 0,
          bg: 0,
          ch: 0,
          cy: 0,
          cz: 0,
          de: 0,
          dk: 0,
          dz: 0,
          ee: 0,
          eg: 0,
          es: 0,
          fi: 0,
          fo: 0,
          fr: 0,
          gg: 0,
          gi: 0,
          gr: 0,
          hr: 0,
          hu: 0,
          ie: 0,
          il: 0,
          im: 0,
          is: 0,
          it: 0,
          je: 0,
          lb: 0,
          li: 0,
          lt: 0,
          lu: 0,
          lv: 0,
          ly: 0,
          ma: 0,
          mc: 0,
          md: 0,
          me: 0,
          mk: 0,
          mt: 0,
          nl: 0,
          no: 0,
          pl: 0,
          ps: 0,
          pt: 0,
          ro: 0,
          rs: 0,
          se: 0,
          si: 0,
          sj: 0,
          sk: 0,
          sm: 0,
          sy: 0,
          tn: 0,
          tr: 0,
          ua: 0,
          uk: 0,
          us: 0,
          va: 0,
          world: 0,
          xk: 0
        },
        warning: 'origins_are_100_percent_unknown'
      },
      packaging: {
        value: -15,
        warning: 'packaging_data_missing'
      },
      production_system: {
        labels: ['en:fairtrade-international'],
        value: 10
      },
      threatened_species: {}
    },
    agribalyse: {
      agribalyse_food_code: '31004',
      agribalyse_proxy_food_code: '31004',
      co2_agriculture: 11.535065,
      co2_consumption: 0,
      co2_distribution: 0.017263204,
      co2_packaging: 0.10402936,
      co2_processing: 0.56768384,
      co2_total: 12.575972694,
      co2_transportation: 0.35193129,
      code: '31004',
      dqr: '2.99',
      ef_agriculture: 0.66750436,
      ef_consumption: 0,
      ef_distribution: 0.0046101581,
      ef_packaging: 0.010330022,
      ef_processing: 0.051117732,
      ef_total: 0.7674436691,
      ef_transportation: 0.033881397,
      is_beverage: 0,
      name_en: 'Milk chocolate bar',
      name_fr: 'Chocolat au lait, tablette',
      score: 39,
      version: '3.1.1'
    },
    grade: 'd',
    grades: {
      ad: 'd',
      al: 'd',
      at: 'd',
      ax: 'd',
      ba: 'd',
      be: 'd',
      bg: 'd',
      ch: 'd',
      cy: 'd',
      cz: 'd',
      de: 'd',
      dk: 'd',
      dz: 'd',
      ee: 'd',
      eg: 'd',
      es: 'd',
      fi: 'd',
      fo: 'd',
      fr: 'd',
      gg: 'd',
      gi: 'd',
      gr: 'd',
      hr: 'd',
      hu: 'd',
      ie: 'd',
      il: 'd',
      im: 'd',
      is: 'd',
      it: 'd',
      je: 'd',
      lb: 'd',
      li: 'd',
      lt: 'd',
      lu: 'd',
      lv: 'd',
      ly: 'd',
      ma: 'd',
      mc: 'd',
      md: 'd',
      me: 'd',
      mk: 'd',
      mt: 'd',
      nl: 'd',
      no: 'd',
      pl: 'd',
      ps: 'd',
      pt: 'd',
      ro: 'd',
      rs: 'd',
      se: 'd',
      si: 'd',
      sj: 'd',
      sk: 'd',
      sm: 'd',
      sy: 'd',
      tn: 'd',
      tr: 'd',
      ua: 'd',
      uk: 'd',
      us: 'd',
      va: 'd',
      world: 'd',
      xk: 'd'
    },
    missing: {
      origins: 1,
      packagings: 1
    },
    missing_data_warning: 1,
    missing_key_data: 1,
    score: 34,
    scores: {
      ad: 34,
      al: 34,
      at: 34,
      ax: 34,
      ba: 34,
      be: 34,
      bg: 34,
      ch: 34,
      cy: 34,
      cz: 34,
      de: 34,
      dk: 34,
      dz: 34,
      ee: 34,
      eg: 34,
      es: 34,
      fi: 34,
      fo: 34,
      fr: 34,
      gg: 34,
      gi: 34,
      gr: 34,
      hr: 34,
      hu: 34,
      ie: 34,
      il: 34,
      im: 34,
      is: 34,
      it: 34,
      je: 34,
      lb: 34,
      li: 34,
      lt: 34,
      lu: 34,
      lv: 34,
      ly: 34,
      ma: 34,
      mc: 34,
      md: 34,
      me: 34,
      mk: 34,
      mt: 34,
      nl: 34,
      no: 34,
      pl: 34,
      ps: 34,
      pt: 34,
      ro: 34,
      rs: 34,
      se: 34,
      si: 34,
      sj: 34,
      sk: 34,
      sm: 34,
      sy: 34,
      tn: 34,
      tr: 34,
      ua: 34,
      uk: 34,
      us: 34,
      va: 34,
      world: 34,
      xk: 34
    },
    status: 'known'
  },
  ecoscore_grade: 'd',
  ecoscore_score: 34,
  ecoscore_tags: ['d'],
  editors_tags: [
    'ecoscore-impact-estimator',
    'kiliweb',
    'lcmortensen',
    'openfoodfacts-contributors',
    'ponkcelot',
    'yuka.sY2b0xO6T85zoF3NwEKvlhF5SuaDmD_dLSXnn2jb6_CtC73xPtZf_4LoAas'
  ],
  emb_codes: '',
  emb_codes_tags: [],
  entry_dates_tags: ['2020-10-07', '2020-10', '2020'],
  expiration_date: '',
  food_groups: 'en:chocolate-products',
  food_groups_tags: ['en:sugary-snacks', 'en:chocolate-products'],
  generic_name: 'Milk chocolate bar',
  generic_name_en: 'Milk chocolate bar',
  id: '0858010005580',
  image_front_small_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.200.jpg',
  image_front_thumb_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.100.jpg',
  image_front_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.400.jpg',
  image_ingredients_small_url:
    'https://images.openfoodfacts.org/images/products/085/801/000/5580/ingredients_en.11.200.jpg',
  image_ingredients_thumb_url:
    'https://images.openfoodfacts.org/images/products/085/801/000/5580/ingredients_en.11.100.jpg',
  image_ingredients_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/ingredients_en.11.400.jpg',
  image_nutrition_small_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/nutrition_en.5.200.jpg',
  image_nutrition_thumb_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/nutrition_en.5.100.jpg',
  image_nutrition_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/nutrition_en.5.400.jpg',
  image_small_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.200.jpg',
  image_thumb_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.100.jpg',
  image_url: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.400.jpg',
  images: {
    '1': {
      sizes: {
        '100': {
          h: 59,
          w: 100
        },
        '400': {
          h: 234,
          w: 400
        },
        full: {
          h: 611,
          w: 1043
        }
      },
      uploaded_t: 1602101650,
      uploader: 'kiliweb'
    },
    '2': {
      sizes: {
        '100': {
          h: 28,
          w: 100
        },
        '400': {
          h: 114,
          w: 400
        },
        full: {
          h: 273,
          w: 961
        }
      },
      uploaded_t: 1602101651,
      uploader: 'kiliweb'
    },
    '3': {
      sizes: {
        '100': {
          h: 26,
          w: 100
        },
        '400': {
          h: 104,
          w: 400
        },
        full: {
          h: 929,
          w: 3590
        }
      },
      uploaded_t: 1640754138,
      uploader: 'ponkcelot'
    },
    '4': {
      sizes: {
        '100': {
          h: 14,
          w: 100
        },
        '400': {
          h: 57,
          w: 400
        },
        full: {
          h: 500,
          w: 3527
        }
      },
      uploaded_t: 1640754168,
      uploader: 'ponkcelot'
    },
    front_en: {
      angle: 0,
      geometry: '0x0--1--1',
      imgid: '1',
      normalize: null,
      rev: '3',
      sizes: {
        '100': {
          h: 59,
          w: 100
        },
        '200': {
          h: 117,
          w: 200
        },
        '400': {
          h: 234,
          w: 400
        },
        full: {
          h: 611,
          w: 1043
        }
      },
      white_magic: null,
      x1: '-1',
      x2: '-1',
      y1: '-1',
      y2: '-1'
    },
    ingredients_en: {
      angle: null,
      coordinates_image_size: '400',
      geometry: '0x0-0-0',
      imgid: '4',
      normalize: null,
      rev: '11',
      sizes: {
        '100': {
          h: 14,
          w: 100
        },
        '200': {
          h: 28,
          w: 200
        },
        '400': {
          h: 57,
          w: 400
        },
        full: {
          h: 500,
          w: 3527
        }
      },
      white_magic: null,
      x1: null,
      x2: null,
      y1: null,
      y2: null
    },
    nutrition_en: {
      angle: 0,
      geometry: '0x0--1--1',
      imgid: '2',
      normalize: null,
      rev: '5',
      sizes: {
        '100': {
          h: 28,
          w: 100
        },
        '200': {
          h: 57,
          w: 200
        },
        '400': {
          h: 114,
          w: 400
        },
        full: {
          h: 273,
          w: 961
        }
      },
      white_magic: null,
      x1: '-1',
      x2: '-1',
      y1: '-1',
      y2: '-1'
    }
  },
  informers_tags: ['yuka.sY2b0xO6T85zoF3NwEKvlhF5SuaDmD_dLSXnn2jb6_CtC73xPtZf_4LoAas', 'kiliweb', 'ponkcelot'],
  ingredients: [
    {
      ciqual_proxy_food_code: '31016',
      ecobalyse_code: 'sugar',
      id: 'en:sugar',
      is_in_taxonomy: 1,
      percent_estimate: 50,
      rank: 1,
      text: 'Sugar',
      vegan: 'yes',
      vegetarian: 'yes'
    },
    {
      ciqual_food_code: '19021',
      ecobalyse_code: 'milk-powder',
      id: 'en:whole-milk-powder',
      is_in_taxonomy: 1,
      percent_estimate: 25,
      rank: 2,
      text: 'dry whole milk',
      vegan: 'no',
      vegetarian: 'yes'
    },
    {
      ciqual_food_code: '16030',
      id: 'en:cocoa-butter',
      is_in_taxonomy: 1,
      percent_estimate: 12.5,
      rank: 3,
      text: 'cocoa butter',
      vegan: 'yes',
      vegetarian: 'yes'
    },
    {
      ciqual_proxy_food_code: '16030',
      id: 'en:cocoa-paste',
      is_in_taxonomy: 1,
      percent_estimate: 6.25,
      rank: 4,
      text: 'cocoa mass',
      vegan: 'yes',
      vegetarian: 'yes'
    },
    {
      ciqual_food_code: '42200',
      id: 'en:soya-lecithin',
      is_in_taxonomy: 1,
      percent_estimate: 3.125,
      rank: 5,
      text: 'soy lecithin',
      vegan: 'yes',
      vegetarian: 'yes'
    },
    {
      ciqual_proxy_food_code: '18100',
      id: 'en:cocoa-solids',
      is_in_taxonomy: 1,
      percent: 32,
      percent_estimate: 3.125,
      rank: 6,
      text: 'Cocoa solids',
      vegan: 'yes',
      vegetarian: 'yes'
    }
  ],
  ingredients_analysis: {
    'en:non-vegan': ['en:whole-milk-powder']
  },
  ingredients_analysis_tags: ['en:palm-oil-free', 'en:non-vegan', 'en:vegetarian'],
  ingredients_from_or_that_may_be_from_palm_oil_n: 0,
  ingredients_from_palm_oil_n: 0,
  ingredients_from_palm_oil_tags: [],
  ingredients_hierarchy: [
    'en:sugar',
    'en:added-sugar',
    'en:disaccharide',
    'en:whole-milk-powder',
    'en:dairy',
    'en:milk-powder',
    'en:cocoa-butter',
    'en:plant',
    'en:cocoa',
    'en:cocoa-paste',
    'en:soya-lecithin',
    'en:e322',
    'en:e322i',
    'en:cocoa-solids'
  ],
  ingredients_lc: 'en',
  ingredients_n: 6,
  ingredients_n_tags: ['6', '1-10'],
  ingredients_non_nutritive_sweeteners_n: 0,
  ingredients_original_tags: [
    'en:sugar',
    'en:whole-milk-powder',
    'en:cocoa-butter',
    'en:cocoa-paste',
    'en:soya-lecithin',
    'en:cocoa-solids'
  ],
  ingredients_percent_analysis: -1,
  ingredients_sweeteners_n: 0,
  ingredients_tags: [
    'en:sugar',
    'en:added-sugar',
    'en:disaccharide',
    'en:whole-milk-powder',
    'en:dairy',
    'en:milk-powder',
    'en:cocoa-butter',
    'en:plant',
    'en:cocoa',
    'en:cocoa-paste',
    'en:soya-lecithin',
    'en:e322',
    'en:e322i',
    'en:cocoa-solids'
  ],
  ingredients_text:
    'Sugar, dry whole milk, cocoa butter, cocoa mass, soy lecithin. May contain egg, tree nuts, wheat and peanut. Cocoa solids: 32% minimum.',
  ingredients_text_en:
    'Sugar, dry whole milk, cocoa butter, cocoa mass, soy lecithin. May contain egg, tree nuts, wheat and peanut. Cocoa solids: 32% minimum.',
  ingredients_text_with_allergens:
    'Sugar, dry whole milk, cocoa butter, cocoa mass, <span class="allergen">soy lecithin</span>. May contain <span class="allergen">egg</span>, <span class="allergen">tree nuts</span>, <span class="allergen">wheat</span> and <span class="allergen">peanut</span>. Cocoa solids: 32% minimum.',
  ingredients_text_with_allergens_en:
    'Sugar, dry whole milk, cocoa butter, cocoa mass, <span class="allergen">soy lecithin</span>. May contain <span class="allergen">egg</span>, <span class="allergen">tree nuts</span>, <span class="allergen">wheat</span> and <span class="allergen">peanut</span>. Cocoa solids: 32% minimum.',
  ingredients_that_may_be_from_palm_oil_n: 0,
  ingredients_that_may_be_from_palm_oil_tags: [],
  ingredients_with_specified_percent_n: 1,
  ingredients_with_specified_percent_sum: 32,
  ingredients_with_unspecified_percent_n: 5,
  ingredients_with_unspecified_percent_sum: 96.875,
  ingredients_without_ciqual_codes: [],
  ingredients_without_ciqual_codes_n: 0,
  ingredients_without_ecobalyse_ids: ['en:cocoa-butter', 'en:cocoa-paste', 'en:cocoa-solids', 'en:soya-lecithin'],
  ingredients_without_ecobalyse_ids_n: 4,
  interface_version_created: '20150316.jqm2',
  interface_version_modified: '20190830',
  known_ingredients_n: 14,
  labels: 'Fair trade,Fairtrade International',
  labels_hierarchy: ['en:fair-trade', 'en:fairtrade-international'],
  labels_lc: 'en',
  labels_old: 'Fair trade, Fairtrade International',
  labels_tags: ['en:fair-trade', 'en:fairtrade-international'],
  lang: 'en',
  languages: {
    'en:english': 6
  },
  languages_codes: {
    en: 6
  },
  languages_hierarchy: ['en:english'],
  languages_tags: ['en:english', 'en:1'],
  last_edit_dates_tags: ['2024-04-16', '2024-04', '2024'],
  last_editor: 'lcmortensen',
  last_image_dates_tags: ['2021-12-29', '2021-12', '2021'],
  last_image_t: 1640754169,
  last_modified_by: 'lcmortensen',
  last_modified_t: 1713258523,
  last_updated_t: 1738794686,
  lc: 'en',
  link: 'https://tonyschocolonely.com/us/en/chocoshop/product/milk-chocolate-32-1',
  main_countries_tags: [],
  manufacturing_places: 'Belgium',
  manufacturing_places_tags: ['belgium'],
  max_imgid: '4',
  minerals_tags: [],
  misc_tags: [
    'en:environmental-score-changed',
    'en:environmental-score-computed',
    'en:environmental-score-extended-data-not-computed',
    'en:environmental-score-grade-changed',
    'en:environmental-score-missing-data-no-packagings',
    'en:environmental-score-missing-data-origins',
    'en:environmental-score-missing-data-packagings',
    'en:environmental-score-missing-data-warning',
    'en:nutriscore-2021-e-2023-e',
    'en:nutriscore-2021-same-as-2023',
    'en:nutriscore-computed',
    'en:nutrition-all-nutriscore-values-known',
    'en:nutrition-fruits-vegetables-legumes-estimate-from-ingredients',
    'en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients',
    'en:packagings-empty',
    'en:packagings-not-complete',
    'en:packagings-number-of-components-0',
    'en:some-ingredients-with-specified-percent'
  ],
  no_nutrition_data: '',
  nova_group: 4,
  nova_group_debug: '',
  nova_groups: '4',
  nova_groups_markers: {
    '3': [
      ['categories', 'en:chocolates'],
      ['ingredients', 'en:sugar'],
      ['categories', 'en:sweet-snacks'],
      ['ingredients', 'en:milk-powder']
    ],
    '4': [['additives', 'en:e322']]
  },
  nova_groups_tags: ['en:4-ultra-processed-food-and-drink-products'],
  nucleotides_tags: [],
  nutrient_levels: {
    fat: 'high',
    salt: 'low',
    'saturated-fat': 'high',
    sugars: 'high'
  },
  nutrient_levels_tags: [
    'en:fat-in-high-quantity',
    'en:saturated-fat-in-high-quantity',
    'en:sugars-in-high-quantity',
    'en:salt-in-low-quantity'
  ],
  nutriments: {
    calcium: 0.078,
    calcium_100g: 0.26,
    calcium_label: 'Calcium',
    calcium_serving: 0.078,
    calcium_unit: '% DV',
    calcium_value: 6,
    carbohydrates: 16,
    carbohydrates_100g: 53.3,
    carbohydrates_serving: 16,
    carbohydrates_unit: 'g',
    carbohydrates_value: 16,
    energy: 669,
    'energy-kcal': 160,
    'energy-kcal_100g': 533,
    'energy-kcal_serving': 160,
    'energy-kcal_unit': 'kcal',
    'energy-kcal_value': 160,
    'energy-kcal_value_computed': 164,
    energy_100g: 2230,
    energy_serving: 669,
    energy_unit: 'kcal',
    energy_value: 160,
    fat: 10,
    fat_100g: 33.3,
    fat_serving: 10,
    fat_unit: 'g',
    fat_value: 10,
    fiber: 1,
    fiber_100g: 3.33,
    fiber_modifier: '<',
    fiber_serving: 1,
    fiber_unit: 'g',
    fiber_value: 1,
    'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
    'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
    'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
    'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
    iron: 0.00108,
    iron_100g: 0.0036,
    iron_label: 'Iron',
    iron_serving: 0.00108,
    iron_unit: '% DV',
    iron_value: 6,
    'nova-group': 4,
    'nova-group_100g': 4,
    'nova-group_serving': 4,
    'nutrition-score-fr': 30,
    'nutrition-score-fr_100g': 30,
    potassium: 0.188,
    potassium_100g: 0.627,
    potassium_label: 'Potassium',
    potassium_serving: 0.188,
    potassium_unit: '% DV',
    potassium_value: 4,
    proteins: 2,
    proteins_100g: 6.67,
    proteins_serving: 2,
    proteins_unit: 'g',
    proteins_value: 2,
    salt: 0.0625,
    salt_100g: 0.208,
    salt_serving: 0.0625,
    salt_unit: 'mg',
    salt_value: 62.5,
    'saturated-fat': 6,
    'saturated-fat_100g': 20,
    'saturated-fat_serving': 6,
    'saturated-fat_unit': 'g',
    'saturated-fat_value': 6,
    sodium: 0.025,
    sodium_100g: 0.0833,
    sodium_serving: 0.025,
    sodium_unit: 'mg',
    sodium_value: 25,
    sugars: 15,
    sugars_100g: 50,
    sugars_serving: 15,
    sugars_unit: 'g',
    sugars_value: 15,
    'vitamin-d': 0.0000012,
    'vitamin-d_100g': 0.000004,
    'vitamin-d_label': 'Vitamin D',
    'vitamin-d_serving': 0.0000012,
    'vitamin-d_unit': '% DV',
    'vitamin-d_value': 6
  },
  nutriments_estimated: {
    alcohol_100g: 0,
    'beta-carotene_100g': 0.000042578125,
    calcium_100g: 0.25012625,
    carbohydrates_100g: 59.8875,
    cholesterol_100g: 0.02675,
    copper_100g: 0.000139125,
    'energy-kcal_100g': 336.84375,
    'energy-kj_100g': 1422.8125,
    energy_100g: 1422.8125,
    fat_100g: 28.6875,
    fiber_100g: 0.921875,
    fructose_100g: 0.00312500000000011,
    galactose_100g: 6e-17,
    glucose_100g: 0.00312500000000011,
    iodine_100g: 0.0000022125,
    iron_100g: 0.00178725,
    lactose_100g: 9.378125,
    magnesium_100g: 0.04329375,
    maltose_100g: 0.00312500000000006,
    manganese_100g: 0.000146525,
    'pantothenic-acid_100g': 0.000593125,
    phosphorus_100g: 0.31,
    phylloquinone_100g: 1.21875e-7,
    polyols_100g: 0.0078125,
    potassium_100g: 0.45346875,
    proteins_100g: 7.55,
    salt_100g: 0.232325,
    'saturated-fat_100g': 4.7125,
    selenium_100g: 0.0000063125,
    sodium_100g: 0.09296,
    starch_100g: 0.265625,
    sucrose_100g: 50.028125,
    sugars_100g: 59.40625,
    'vitamin-a_100g': 0.000057,
    'vitamin-b12_100g': 8.125e-7,
    'vitamin-b1_100g': 0.000084875,
    'vitamin-b2_100g': 0.00036825,
    'vitamin-b6_100g': 0.00007515625,
    'vitamin-b9_100g': 0.00001259375,
    'vitamin-c_100g': 0.0025078125,
    'vitamin-d_100g': 3.853125e-7,
    'vitamin-e_100g': 0.0015421875,
    'vitamin-pp_100g': 0.0001984375,
    water_100g: 0.825625,
    zinc_100g: 0.0011875
  },
  nutriscore: {
    '2021': {
      category_available: 1,
      data: {
        energy: 2230,
        energy_points: 6,
        energy_value: 2230,
        fiber: 3.33,
        fiber_points: 3,
        fiber_value: 3.33,
        fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
        fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
        fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
        is_beverage: 0,
        is_cheese: 0,
        is_fat: 0,
        is_water: 0,
        negative_points: 26,
        positive_points: 3,
        proteins: 6.67,
        proteins_points: 4,
        proteins_value: 6.67,
        saturated_fat: 20,
        saturated_fat_points: 10,
        saturated_fat_value: 20,
        sodium: 83.3,
        sodium_points: 0,
        sodium_value: 83.3,
        sugars: 50,
        sugars_points: 10,
        sugars_value: 50
      },
      grade: 'e',
      nutrients_available: 1,
      nutriscore_applicable: 1,
      nutriscore_computed: 1,
      score: 23
    },
    '2023': {
      category_available: 1,
      data: {
        components: {
          negative: [
            {
              id: 'energy',
              points: 6,
              points_max: 10,
              unit: 'kJ',
              value: 2230
            },
            {
              id: 'sugars',
              points: 14,
              points_max: 15,
              unit: 'g',
              value: 50
            },
            {
              id: 'saturated_fat',
              points: 10,
              points_max: 10,
              unit: 'g',
              value: 20
            },
            {
              id: 'salt',
              points: 1,
              points_max: 20,
              unit: 'g',
              value: 0.21
            }
          ],
          positive: [
            {
              id: 'fiber',
              points: 1,
              points_max: 5,
              unit: 'g',
              value: 3.33
            },
            {
              id: 'fruits_vegetables_legumes',
              points: 0,
              points_max: 5,
              unit: '%',
              value: 0
            }
          ]
        },
        count_proteins: 0,
        count_proteins_reason: 'negative_points_greater_than_or_equal_to_11',
        is_beverage: 0,
        is_cheese: 0,
        is_fat_oil_nuts_seeds: 0,
        is_red_meat_product: 0,
        is_water: 0,
        negative_points: 31,
        negative_points_max: 55,
        positive_nutrients: ['fiber', 'fruits_vegetables_legumes'],
        positive_points: 1,
        positive_points_max: 10
      },
      grade: 'e',
      nutrients_available: 1,
      nutriscore_applicable: 1,
      nutriscore_computed: 1,
      score: 30
    }
  },
  nutriscore_2021_tags: ['e'],
  nutriscore_2023_tags: ['e'],
  nutriscore_data: {
    components: {
      negative: [
        {
          id: 'energy',
          points: 6,
          points_max: 10,
          unit: 'kJ',
          value: 2230
        },
        {
          id: 'sugars',
          points: 14,
          points_max: 15,
          unit: 'g',
          value: 50
        },
        {
          id: 'saturated_fat',
          points: 10,
          points_max: 10,
          unit: 'g',
          value: 20
        },
        {
          id: 'salt',
          points: 1,
          points_max: 20,
          unit: 'g',
          value: 0.21
        }
      ],
      positive: [
        {
          id: 'fiber',
          points: 1,
          points_max: 5,
          unit: 'g',
          value: 3.33
        },
        {
          id: 'fruits_vegetables_legumes',
          points: 0,
          points_max: 5,
          unit: '%',
          value: 0
        }
      ]
    },
    count_proteins: 0,
    count_proteins_reason: 'negative_points_greater_than_or_equal_to_11',
    grade: 'e',
    is_beverage: 0,
    is_cheese: 0,
    is_fat_oil_nuts_seeds: 0,
    is_red_meat_product: 0,
    is_water: 0,
    negative_points: 31,
    negative_points_max: 55,
    positive_nutrients: ['fiber', 'fruits_vegetables_legumes'],
    positive_points: 1,
    positive_points_max: 10,
    score: 30
  },
  nutriscore_grade: 'e',
  nutriscore_score: 30,
  nutriscore_score_opposite: -30,
  nutriscore_tags: ['e'],
  nutriscore_version: '2023',
  nutrition_data: 'on',
  nutrition_data_per: 'serving',
  nutrition_data_prepared: '',
  nutrition_data_prepared_per: '100g',
  nutrition_grade_fr: 'e',
  nutrition_grades: 'e',
  nutrition_grades_tags: ['e'],
  nutrition_score_beverage: 0,
  nutrition_score_debug: '',
  nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients: 1,
  nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients_value: 0,
  nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients: 1,
  nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value: 0,
  origin: '',
  origin_en: '',
  origins: '',
  origins_hierarchy: [],
  origins_lc: 'en',
  origins_tags: [],
  other_nutritional_substances_tags: [],
  packaging: '',
  packaging_hierarchy: [],
  packaging_lc: 'en',
  packaging_materials_tags: [],
  packaging_old: '',
  packaging_recycling_tags: [],
  packaging_shapes_tags: [],
  packaging_tags: [],
  packaging_text: '',
  packaging_text_en: '',
  packagings: [],
  packagings_complete: 0,
  packagings_materials: {},
  photographers_tags: ['kiliweb', 'ponkcelot'],
  pnns_groups_1: 'Sugary snacks',
  pnns_groups_1_tags: ['sugary-snacks', 'known'],
  pnns_groups_2: 'Chocolate products',
  pnns_groups_2_tags: ['chocolate-products', 'known'],
  popularity_key: 23900000008,
  popularity_tags: [
    'top-100000-scans-2023',
    'at-least-5-scans-2023',
    'top-75-percent-scans-2023',
    'top-80-percent-scans-2023',
    'top-85-percent-scans-2023',
    'top-90-percent-scans-2023',
    'top-5000-us-scans-2023',
    'top-10000-us-scans-2023',
    'top-50000-us-scans-2023',
    'top-100000-us-scans-2023',
    'top-country-us-scans-2023',
    'at-least-5-us-scans-2023',
    'top-100000-scans-2024',
    'at-least-5-scans-2024',
    'top-75-percent-scans-2024',
    'top-80-percent-scans-2024',
    'top-85-percent-scans-2024',
    'top-90-percent-scans-2024',
    'top-5000-us-scans-2024',
    'top-10000-us-scans-2024',
    'top-50000-us-scans-2024',
    'top-100000-us-scans-2024',
    'top-country-us-scans-2024',
    'at-least-5-us-scans-2024',
    'top-5000-au-scans-2024',
    'top-10000-au-scans-2024',
    'top-50000-au-scans-2024',
    'top-100000-au-scans-2024'
  ],
  product_name: '32% milk chocolate',
  product_name_en: '32% milk chocolate',
  product_quantity: '180',
  product_quantity_unit: 'g',
  product_type: 'food',
  purchase_places: 'United States',
  purchase_places_tags: ['united-states'],
  quantity: '180 g',
  removed_countries_tags: [],
  rev: 17,
  scans_n: 8,
  schema_version: 996,
  selected_images: {
    front: {
      display: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.400.jpg'
      },
      small: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.200.jpg'
      },
      thumb: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/front_en.3.100.jpg'
      }
    },
    ingredients: {
      display: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/ingredients_en.11.400.jpg'
      },
      small: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/ingredients_en.11.200.jpg'
      },
      thumb: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/ingredients_en.11.100.jpg'
      }
    },
    nutrition: {
      display: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/nutrition_en.5.400.jpg'
      },
      small: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/nutrition_en.5.200.jpg'
      },
      thumb: {
        en: 'https://images.openfoodfacts.org/images/products/085/801/000/5580/nutrition_en.5.100.jpg'
      }
    }
  },
  serving_quantity: '30',
  serving_quantity_unit: 'g',
  serving_size: '30 g',
  sortkey: 1602101652,
  states:
    'en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:packaging-photo-to-be-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded',
  states_hierarchy: [
    'en:to-be-completed',
    'en:nutrition-facts-completed',
    'en:ingredients-completed',
    'en:expiration-date-to-be-completed',
    'en:packaging-code-to-be-completed',
    'en:characteristics-to-be-completed',
    'en:origins-to-be-completed',
    'en:categories-completed',
    'en:brands-completed',
    'en:packaging-to-be-completed',
    'en:quantity-completed',
    'en:product-name-completed',
    'en:photos-to-be-validated',
    'en:packaging-photo-to-be-selected',
    'en:nutrition-photo-selected',
    'en:ingredients-photo-selected',
    'en:front-photo-selected',
    'en:photos-uploaded'
  ],
  states_tags: [
    'en:to-be-completed',
    'en:nutrition-facts-completed',
    'en:ingredients-completed',
    'en:expiration-date-to-be-completed',
    'en:packaging-code-to-be-completed',
    'en:characteristics-to-be-completed',
    'en:origins-to-be-completed',
    'en:categories-completed',
    'en:brands-completed',
    'en:packaging-to-be-completed',
    'en:quantity-completed',
    'en:product-name-completed',
    'en:photos-to-be-validated',
    'en:packaging-photo-to-be-selected',
    'en:nutrition-photo-selected',
    'en:ingredients-photo-selected',
    'en:front-photo-selected',
    'en:photos-uploaded'
  ],
  stores: '',
  stores_tags: [],
  traces: 'en:eggs,en:gluten,en:milk,en:nuts,en:peanuts,en:soybeans',
  traces_from_ingredients: 'egg, tree nuts, wheat, peanut',
  traces_from_user: '(en) en:eggs,en:gluten,en:milk,en:nuts,en:peanuts,en:soybeans',
  traces_hierarchy: ['en:eggs', 'en:gluten', 'en:milk', 'en:nuts', 'en:peanuts', 'en:soybeans'],
  traces_lc: 'en',
  traces_tags: ['en:eggs', 'en:gluten', 'en:milk', 'en:nuts', 'en:peanuts', 'en:soybeans'],
  unique_scans_n: 8,
  unknown_ingredients_n: 0,
  unknown_nutrients_tags: [],
  update_key: 'sort',
  vitamins_tags: [],
  weighers_tags: []
};
