import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
import { ReactNode } from 'react';

import { Root } from '@/components/main';
import { I18nProvider } from '@/core/i18n/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" />
      </head>
      <body>
        <I18nProvider>
          <Root>{children}</Root>
        </I18nProvider>
      </body>
    </html>
  );
}
