on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/github_fit_bot/fit-tracker-bot
            eval `ssh-agent -s` || true
            ssh-add ~/.ssh/fit_tg_bot
            git stash || true
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
